// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMAYEt9yQYLVnFZnnRExVADeujRmVAZW4',
    appId: '1:1076153756387:web:993c2c27100b352846f3d6',
    messagingSenderId: '1076153756387',
    projectId: 'smart-worklife-15f63',
    authDomain: 'smart-worklife-15f63.firebaseapp.com',
    storageBucket: 'smart-worklife-15f63.firebasestorage.app',
    measurementId: 'G-8CKL5W5J3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7IIOUk199j7R248kJhpcAhf2zxJADKBs',
    appId: '1:1076153756387:android:bc990c59cd9287aa46f3d6',
    messagingSenderId: '1076153756387',
    projectId: 'smart-worklife-15f63',
    storageBucket: 'smart-worklife-15f63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRYSVtVMLAES_ckbQ4sdyCjEkzC_zMew',
    appId: '1:1076153756387:ios:16691f16e95f076e46f3d6',
    messagingSenderId: '1076153756387',
    projectId: 'smart-worklife-15f63',
    storageBucket: 'smart-worklife-15f63.firebasestorage.app',
    iosClientId: '1076153756387-cfrk1gn4c09hoismh34ait3dj1htbc8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.worklifeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRYSVtVMLAES_ckbQ4sdyCjEkzC_zMew',
    appId: '1:1076153756387:ios:16691f16e95f076e46f3d6',
    messagingSenderId: '1076153756387',
    projectId: 'smart-worklife-15f63',
    storageBucket: 'smart-worklife-15f63.firebasestorage.app',
    iosClientId: '1076153756387-cfrk1gn4c09hoismh34ait3dj1htbc8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.worklifeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMAYEt9yQYLVnFZnnRExVADeujRmVAZW4',
    appId: '1:1076153756387:web:c3ca1a6847b2b05146f3d6',
    messagingSenderId: '1076153756387',
    projectId: 'smart-worklife-15f63',
    authDomain: 'smart-worklife-15f63.firebaseapp.com',
    storageBucket: 'smart-worklife-15f63.firebasestorage.app',
    measurementId: 'G-Y8S5N86XRC',
  );
}
